/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

public class LibraryTest {

    @Test public void testSomeLibraryMethod() throws IOException {

        StringBuilder sb = new StringBuilder();

        //File file = new File("C:/Users/y_sazankov/eclipse-java/TLV_Parser/tlv/Currency.pst");
        System.out.println("Hi!");
	    //if (!file.exists()){
	    //    throw new FileNotFoundException(file.getName());
	    //}
	    Path path = Paths.get("C:/Users/y_sazankov/eclipse-java/TLV_Parser/tlv/Currency.pst");
	    byte[] data = Files.readAllBytes(path);
        ParamsParser.init();
        CurrencyPreset preset = ParamsParser.parse(data, CurrencyPreset.class);
    }
    
    private static byte[] toBytes(char[] chars) {
        CharBuffer charBuffer = CharBuffer.wrap(chars);
        ByteBuffer byteBuffer = Charset.forName("UTF-8").encode(charBuffer);
        byte[] bytes = Arrays.copyOfRange(byteBuffer.array(),
                byteBuffer.position(), byteBuffer.limit());
        Arrays.fill(charBuffer.array(), '\u0000'); // clear sensitive data
        Arrays.fill(byteBuffer.array(), (byte) 0); // clear sensitive data
        return bytes;
    }
}
